'use client'
import Head from 'next/head'
import Button from '@mui/material/Button'
import { useTheme } from '@emotion/react'
import { useSettings } from 'src/hooks/useSettings'
import { Typography } from '@mui/material'

export default function Home() {
  const theme = useTheme()
  const { settings } = useSettings()
  console.log('theme ', { theme, settings })
  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Button variant='contained'>Hello world</Button>
      <Typography>Update ne </Typography>
    </>
  )
}
